### ISSUE TITLE
does not find pyew and r2

### ISSUE THREAD

**Issue by 230v** [inguma/bokken#11]
![screenshot_2015-05-22_19-07-47](https://cloud.githubusercontent.com/assets/9416005/7774702/f1201e9c-00b5-11e5-9579-011663cbc507.png)

**Comment by XVilka** [comment]
@230v have you installed radare2-bindings?

**Comment by 230v** [comment]
r2-bindings install from git

**Comment by 230v** [comment]
$ pacman -Qi radare2-bindings-git
Name           : radare2-bindings-git
Version        : 20150522.467.8cfe364-1
Description    : Language bindings for radare2 (git version)
Architecture   : i686
URL            : https://radare.org
Licenses       : LGPL
Groups         : None
Provides       : r2-bindings
Depends On     : radare2-git  valabind-git
Optional Deps  : None
Required By    : bokken
Optional For   : None
Conflicts With : r2-bindings
Replaces       : None
Installed Size :   3.38 MiB
Packager       : Unknown Packager
Build Date     : Fri 22 May 2015 06:52:07 PM EEST
Install Date   : Fri 22 May 2015 06:54:37 PM EEST
Install Reason : Explicitly installed
Install Script : No
Validated By   : None

**Comment by XVilka** [comment]
230v: can you show the files paths it installed? (r2-bindings)

**Comment by 230v** [comment]
radare2-bindings-git /usr/
radare2-bindings-git /usr/lib/
radare2-bindings-git /usr/lib/python2.7/
radare2-bindings-git /usr/lib/python2.7/site-packages/
radare2-bindings-git /usr/lib/python2.7/site-packages/r2/
radare2-bindings-git /usr/lib/python2.7/site-packages/r2/__init__.py
radare2-bindings-git /usr/lib/python2.7/site-packages/r2/_r_asm.so
radare2-bindings-git /usr/lib/python2.7/site-packages/r2/_r_bin.so
radare2-bindings-git /usr/lib/python2.7/site-packages/r2/_r_core.so
radare2-bindings-git /usr/lib/python2.7/site-packages/r2/r_asm.py
radare2-bindings-git /usr/lib/python2.7/site-packages/r2/r_bin.py
radare2-bindings-git /usr/lib/python2.7/site-packages/r2/r_core.py
radare2-bindings-git /usr/lib/radare2/
radare2-bindings-git /usr/lib/radare2/0.9.9-git/
radare2-bindings-git /usr/lib/radare2/0.9.9-git/lang_duktape.so
radare2-bindings-git /usr/lib/radare2/0.9.9-git/lang_python.so
radare2-bindings-git /usr/share/
radare2-bindings-git /usr/share/vala/
radare2-bindings-git /usr/share/vala/vapi/
radare2-bindings-git /usr/share/vala/vapi/libr.deps
radare2-bindings-git /usr/share/vala/vapi/libr.vapi
radare2-bindings-git /usr/share/vala/vapi/r_anal.deps
radare2-bindings-git /usr/share/vala/vapi/r_anal.vapi
radare2-bindings-git /usr/share/vala/vapi/r_asm.deps
radare2-bindings-git /usr/share/vala/vapi/r_asm.vapi
radare2-bindings-git /usr/share/vala/vapi/r_bin.deps
radare2-bindings-git /usr/share/vala/vapi/r_bin.vapi
radare2-bindings-git /usr/share/vala/vapi/r_bp.deps
radare2-bindings-git /usr/share/vala/vapi/r_bp.vapi
radare2-bindings-git /usr/share/vala/vapi/r_cmd.deps
radare2-bindings-git /usr/share/vala/vapi/r_cmd.vapi
radare2-bindings-git /usr/share/vala/vapi/r_config.vapi
radare2-bindings-git /usr/share/vala/vapi/r_cons.vapi
radare2-bindings-git /usr/share/vala/vapi/r_core.deps
radare2-bindings-git /usr/share/vala/vapi/r_core.vapi
radare2-bindings-git /usr/share/vala/vapi/r_crypto.vapi
radare2-bindings-git /usr/share/vala/vapi/r_db.deps
radare2-bindings-git /usr/share/vala/vapi/r_db.vapi
radare2-bindings-git /usr/share/vala/vapi/r_debug.deps
radare2-bindings-git /usr/share/vala/vapi/r_debug.vapi
radare2-bindings-git /usr/share/vala/vapi/r_diff.vapi
radare2-bindings-git /usr/share/vala/vapi/r_egg.deps
radare2-bindings-git /usr/share/vala/vapi/r_egg.vapi
radare2-bindings-git /usr/share/vala/vapi/r_flags.deps
radare2-bindings-git /usr/share/vala/vapi/r_flags.vapi
radare2-bindings-git /usr/share/vala/vapi/r_fs.deps
radare2-bindings-git /usr/share/vala/vapi/r_fs.vapi
radare2-bindings-git /usr/share/vala/vapi/r_hash.vapi
radare2-bindings-git /usr/share/vala/vapi/r_io.deps
radare2-bindings-git /usr/share/vala/vapi/r_io.vapi
radare2-bindings-git /usr/share/vala/vapi/r_lang.vapi
radare2-bindings-git /usr/share/vala/vapi/r_magic.deps
radare2-bindings-git /usr/share/vala/vapi/r_magic.vapi
radare2-bindings-git /usr/share/vala/vapi/r_parse.deps
radare2-bindings-git /usr/share/vala/vapi/r_parse.vapi
radare2-bindings-git /usr/share/vala/vapi/r_print.vapi
radare2-bindings-git /usr/share/vala/vapi/r_reg.deps
radare2-bindings-git /usr/share/vala/vapi/r_reg.vapi
radare2-bindings-git /usr/share/vala/vapi/r_search.deps
radare2-bindings-git /usr/share/vala/vapi/r_search.vapi
radare2-bindings-git /usr/share/vala/vapi/r_socket.vapi
radare2-bindings-git /usr/share/vala/vapi/r_syscall.vapi
radare2-bindings-git /usr/share/vala/vapi/r_util.vapi

**Comment by XVilka** [comment]
@230v looks good from the radare2 side.

**Comment by Jo-Con-El** [comment]
Are you running bokken from HEAD or the 1.7 release?
Can you run this?
$ python
Python 2.7.9 (default, blahblah)
>>> import pyew
>>> import r2

**Comment by 230v** [comment]
This is a problem in the Arch Linux, pyew installed in /opt/pyew/, but not added in global PYTHONPATH. Sorry. Fu~~ng arch...

**Comment by Jo-Con-El** [comment]
:laughing:

**Comment by XVilka** [comment]
@230v - but what about radare2? does the import r_core works ok?

**Comment by 230v** [comment]
@XVilka 
$ python2 -c "from r2 import r_core"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/r2/r_core.py", line 339, in <module>
    class RAnalCond(Structure): #19
  File "/usr/lib/python2.7/site-packages/r2/r_core.py", line 342, in RAnalCond
    ('arg', RAnalValue * 2),
NameError: name 'RAnalValue' is not defined

**Comment by XVilka** [comment]
@230v: ok, thats our fault.

**Comment by Jo-Con-El** [comment]
@xvilka, do you guys make the Arch bindings?

**Comment by XVilka** [comment]
@Jo-Con-El that's 3rd party maintainter I think
