### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by hachzz** [inguma/bokken#16]
Hello,
im very like ur project bokken, but when i run it, this error show up all the times...

here is log:
[hungpv@nop bokken-master]$ ./bokken
	Python version...	OK
	Radare availability...	OK
	GTK UI dependencies...	OK
	GtkSourceView2...	OK
	Graphviz binaries...	OK
Starting bokken 1.9-dev, running on:
  Python version:
    2.7.10 (default, May 26 2015, 04:16:29) 
    [GCC 5.1.0]
  GTK version: 2.24.28
  PyGTK version: 2.24.0

Traceback (most recent call last):
 
  File "./bokken.py", line 76, in <module>
    bokken()
  File "./bokken.py", line 68, in bokken
    import ui.main as main
  File "/home/hungpv/Hoc/bokken-master/ui/main.py", line 41, in <module>
    import ui.textviews as textviews
  File "/home/hungpv/Hoc/bokken-master/ui/textviews.py", line 29, in <module>
    import ui.rightnotebook as rightnotebook
  File "/home/hungpv/Hoc/bokken-master/ui/rightnotebook.py", line 22, in <module>
    import ui.graph
  File "/home/hungpv/Hoc/bokken-master/ui/graph.py", line 22, in <module>
    from PIL import Image
ImportError: No module named PIL

please help me fix this, thank  you! :)

**Comment by XVilka** [comment]
PIL is deprecated for both pythons, probably bokken authors want to migrate on pillow.

**Comment by hachzz** [comment]
^
so, how to fix it? pls show me how to solve...

**Comment by XVilka** [comment]
@hachzz https://pillow.readthedocs.org/porting-pil-to-pillow.html

**Comment by XVilka** [comment]
@hachzz and ofc install pillow package from your distributive

**Comment by hachzz** [comment]
omg, after install python-pillow, problem solved...
i dont read the logs carefully.
thank you @XVilka so much !:)
