### ISSUE TITLE
Dead links to rnicrosoft.com

### ISSUE THREAD

**Issue by yaps8** [inguma/bokken#17]
Hello,
This is a very minor issue (and easy to fix).
In the (useful) Reference Sheet for x86 Assembler, the "About" buttons shows:
"The data for this cheat sheet has been borrowed from:
http://www.rnicrosoft.net
The original cheat sheet can be downloaded from here (http://www.rnicrosoft.net/docs/X86_Win32_Reverse_Engineering_Cheat_Sheet.pdf)"

But the domain (rnicrosoft.net) seems to be for sale so these are dead links.

**Comment by hteso** [comment]
You are right, we will modify the dialog for the next release.

Thanks for the heads up!

**Comment by Jo-Con-El** [comment]
@hteso, I'm going to link this to http://www.jegerlehner.ch/intel.  I think it's a nice sheet.  You found the original sheet so you have veto if you don't like it.

**Comment by Jo-Con-El** [comment]
Closed in 5ddb2d4e.
