### ISSUE TITLE
inguma.eu certificate expired

### ISSUE THREAD

**Issue by blshkv** [inguma/bokken#26]
Sorry but  I"m too lazy to register at your website.
The cert has expired, please renew.

**Comment by hteso** [comment]
We are working on it, we expect to have it fixed soon :)

**Comment by Jo-Con-El** [comment]
Sorry, this is fixed.

**Comment by bill-e-ghote** [comment]
I'm also too lazy to register at your website. You should re-open this bug. Your certificate expired again, and has been expired now for over six months.

**Comment by XVilka** [comment]
@bill-e-ghote - just forget about this project, it was abandoned in favor of Cutter - Qt GUI for radare2 (formerly known as Iaito) https://github.com/radareorg/cutter/
![](https://raw.githubusercontent.com/radareorg/cutter/master/docs/screenshot.png)
