### ISSUE TITLE
Exit after opening a binary file.

### ISSUE THREAD

**Issue by tahaaltuntas** [inguma/bokken#6]
After selecting an elf file for an input, it crashes with this error:

[taltuntas@localhost bokken-1.6]$ ./bokken
        Python version...       OK
Checking:
        Pyew availability...    D'oh!
You need pyew in order to use pyew backend in binaries and PDFs. Download it from its web:
    - http://code.google.com/p/pyew/

        Radare availability...  OK
        GTK UI dependencies...  OK
        GtkSourceView2...       OK
        Psyco availability...   D'oh!
No psyco module found. It's recomended to use it to improve performance

        Tidy availability...    D'oh!
No tidy module found. HTTP code won't be properly formatted

Starting bokken, running on:
  Python version:
    2.7.5 (default, Jun 17 2014, 18:11:42)
    [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
  GTK version: 2.24.22
  PyGTK version: 2.24.0

/home/taltuntas/bokken/bokken-1.6/ui/main.py:78: GtkWarning: Attempting to store changes into `/home/taltuntas/.local/share/recently-used.xbel', but failed: Failed to create file '/home/taltuntas/.local/share/recently-used.xbel.CIHZWX': No such file or directory
  resp = dialog.run()
/home/taltuntas/bokken/bokken-1.6/ui/main.py:78: GtkWarning: Attempting to set the permissions of `/home/taltuntas/.local/share/recently-used.xbel', but failed: No such file or directory
  resp = dialog.run()
Traceback (most recent call last):
  File "./bokken.py", line 35, in <module>
    main.main('', '')
  File "/home/taltuntas/bokken/bokken-1.6/ui/main.py", line 411, in main
    MainApp(target, backend)
  File "/home/taltuntas/bokken/bokken-1.6/ui/main.py", line 103, in __init__
    self.load_file(self.target)
  File "/home/taltuntas/bokken/bokken-1.6/ui/main.py", line 182, in load_file
    self.uicore.load_file(target)
  File "/home/taltuntas/bokken/bokken-1.6/ui/radare_core.py", line 120, in load_file
    self.core.bin_load(None)
TypeError: RCore_bin_load expected 3 arguments, got 2

Do you have any idea?

**Comment by hteso** [comment]
Looks like your are using bokken with a wrong radare2 version. Try Bokken 1.7 with radare2 0.9.8, those are the latest supported. More info: www.bokken.re

**Comment by Jo-Con-El** [comment]
@tahaaltuntas, any success?

**Comment by slorquet** [comment]
I have the same issue, with a radare2 compiled from sources.

do you have an ETA for a bokken version that works with radare2 HEAD?

**Comment by Jo-Con-El** [comment]
The tip of the repo works with r2 0.9.9-git.

**Comment by tahaaltuntas** [comment]
Sorry for late response. I've reinstalled Bokken 1.7 and radare2 0.9.8 everything works fine. Not produced again. I'm not sure radare2 version when error occurred but probably as you mentioned radare2 version was not supported by Bokken. Thanks for your replies.

**Comment by Jo-Con-El** [comment]
Great to hear!  I'll go ahead and close this issue.  Please reopen if necessary.
